### ISSUE TITLE
Social image

### ISSUE THREAD

**Issue by bozdoz** [bozdoz/remy-design#1]
Needs a social image: 

info: https://www.kapwing.com/resources/what-is-an-og-image-make-and-format-og-images-for-your-blog-or-webpage/

check: https://metatags.io/

**Comment by bozdoz** [comment]
Hey @jeremyrcormier

**Comment by bozdoz** [comment]
1200:630 resolution is recommended

**Comment by jeremyrcormier** [comment]
![RD_Thumbnail](https://user-images.githubusercontent.com/111755170/186007384-039fd7a4-e36f-42c3-ab30-1c2db5766277.svg)

**Comment by jeremyrcormier** [comment]
![RD_Thumbnail](https://user-images.githubusercontent.com/111755170/186007486-dc308294-e0be-485d-b953-b32c6bc616ef.svg)

**Comment by jeremyrcormier** [comment]
That should do it..

**Comment by bozdoz** [comment]
What a beaut, throw that in the public/images folder why don't ya?
